all_joints:
- - 0
- - 1
- - 2
all_joints_names:
- Nose
- Left Paw
- Right Paw
batch_size: 1
cropratio: 0.4
dataset: training-datasets\iteration-1\UnaugmentedDataSet_Paw TrackingOct14\Paw Tracking_Gianna85shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_101.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-1\UnaugmentedDataSet_Paw TrackingOct14\Documentation_data-Paw
  Tracking_85shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_101
num_joints: 3
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: G:\String Pulling Analysis\Paw Tracking-Gianna-2020-10-14
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
